export const Users = [
  {
    "id": 1,
    "first_name": "john",
    "last_name": "dulo",
    "email": "john@gmail.com",
    "gender": "male",
  },
  {
    "id": 2,
    "first_name": "khali",
    "last_name": "dale",
    "email": "Kali@gmail.com",
    "gender": "female",
  },
  {
    "id": 3,
    "first_name": "jack",
    "last_name": "david",
    "email": "jack@gmail.com",
    "gender": "male",
  },
  {
    "id": 4,
    "first_name": "rose",
    "last_name": "fozzy",
    "email": "rose@gmail.com",
    "gender": "female",
  },
  {
    "id": 5,
    "first_name": "jeko",
    "last_name": "breake",
    "email": "Jeko@gmail.com",
    "gender": "male",
  },
  {
    "id": 6,
    "first_name": "rio",
    "last_name": "drane",
    "email": "rioo@gmail.com",
    "gender": "male",
  },
  {
    "id": 7,
    "first_name": "Jolie",
    "last_name": "cader",
    "email": "jolie@gmail.com",
    "gender": "female",
  },
  {
    "id": 8,
    "first_name": "rolia",
    "last_name": "caroline",
    "email": "rolia@gmail.com",
    "gender": "female",
  },
  {
    "id": 9,
    "first_name": "rolexa",
    "last_name": "ferds",
    "email": "rolexa@gmail.com",
    "gender": "female",
  },
]